allowBuilds:
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@mswjs/interceptors@0.45.5'
  - '@typescript-eslint/eslint-plugin@8.71.0'
  - '@typescript-eslint/parser@8.71.0'
  - '@typescript-eslint/project-service@8.71.0'
  - '@typescript-eslint/scope-manager@8.71.0'
  - '@typescript-eslint/tsconfig-utils@8.71.0'
  - '@typescript-eslint/type-utils@8.71.0'
  - '@typescript-eslint/types@8.71.0'
  - '@typescript-eslint/typescript-estree@8.71.0'
  - '@typescript-eslint/utils@8.71.0'
  - '@typescript-eslint/visitor-keys@8.71.0'
  - msw@3.0.0
  - typescript-eslint@8.71.0
